### ISSUE TITLE
Improvement: Update documentation

### ISSUE THREAD

**Issue by TheSmartHyena** [vinubabu323/strapi-plugin-excel-export#3]
Hello, first of all, great plugin thanks. 
Im creating this issue to maybe help some people. 
Be sure to have the field "relation" set to empty even if you have any relation in the tables you want to export. Not having it results into 500 internal errors. 

In my case a simple export of a newsletter table: 

`module.exports = {
    config: {
      "api::newsletter.newsletter": {
        columns: [
          "email",
        ],
        locale: "false",
        relation: {}
      },
    },
  };`

Maybe write it in the documentation ? I'm pretty sure it's confusing.

**Comment by wendelsantosd** [comment]
> Hello, first of all, great plugin thanks. Im creating this issue to maybe help some people. Be sure to have the field "relation" set to empty even if you have any relation in the tables you want to export. Not having it results into 500 internal errors.
> 
> In my case a simple export of a newsletter table:
> 
> `module.exports = { config: { "api::newsletter.newsletter": { columns: [ "email", ], locale: "false", relation: {} }, }, };`
> 
> Maybe write it in the documentation ? I'm pretty sure it's confusing.

This helped me, thanks.

**Comment by vinubabu323** [comment]
updated
