### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by FaijanSaifi99** [vinubabu323/strapi-plugin-excel-export#4]
npm install strapi-plugin-excel-export-2024

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: corporate-blog-template@0.1.0
npm ERR! Found: react@18.3.1
npm ERR! node_modules/react
npm ERR!   react@"^18.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from strapi-plugin-excel-export-2024@1.0.6
npm ERR! node_modules/strapi-plugin-excel-export-2024
npm ERR!   strapi-plugin-excel-export-2024@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by vinubabu323** [comment]
npm install strapi-plugin-excel-export-2024 --force

Use this command or try to fix the upstream dependency conflict
